/* Script para crear la base de datos y sus tablas */
const script_create_model = `
-- CREAR BASE DE DATOS

CREATE SCHEMA IF NOT EXISTS bd1_p1;

--  TABLA PARTIDO

CREATE TABLE IF NOT EXISTS bd1_p1.PARTIDO (
  id INTEGER NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  siglas VARCHAR(10) NOT NULL,
  fundacion DATE NOT NULL,
  PRIMARY KEY (id) 
);

-- TABLA CARGO

CREATE TABLE IF NOT EXISTS bd1_p1.CARGO (
  id INTEGER NOT NULL AUTO_INCREMENT,
  cargo VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);


-- TABLA CANDIDATO

CREATE TABLE IF NOT EXISTS bd1_p1.CANDIDATO (
  id INTEGER NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  fecha_nac DATE NOT NULL,
  id_cargo INTEGER NOT NULL,
  id_partido INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_cargo) REFERENCES bd1_p1.CARGO (id),
  FOREIGN KEY (id_partido) REFERENCES bd1_p1.PARTIDO (id)
);


-- TABLA CIUDADANO

CREATE TABLE IF NOT EXISTS bd1_p1.CIUDADANO (
  id VARCHAR(13) NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  direccion VARCHAR(100) NOT NULL,
  telefono VARCHAR(10) NOT NULL,
  edad INTEGER NOT NULL,
  genero VARCHAR(1) NOT NULL,
  PRIMARY KEY (id)
);

-- TABLA DEPARTAMENTO

CREATE TABLE IF NOT EXISTS bd1_p1.DEPARTAMENTO (
  id INTEGER NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

-- TABLA MESA

CREATE TABLE IF NOT EXISTS bd1_p1.MESA (
  id INTEGER NOT NULL AUTO_INCREMENT,
  id_dep INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_dep) REFERENCES bd1_p1.DEPARTAMENTO (id)
);

-- TABLA VOTO

CREATE TABLE IF NOT EXISTS bd1_p1.VOTO (
  id INTEGER NOT NULL AUTO_INCREMENT,
  fechahora DATETIME NOT NULL,
  dpi VARCHAR(13) NOT NULL,
  id_mesa INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (dpi) REFERENCES bd1_p1.CIUDADANO (id),
  FOREIGN KEY (id_mesa) REFERENCES bd1_p1.MESA (id)
);

-- TABLA DETALLE VOTO

CREATE TABLE IF NOT EXISTS bd1_p1.DETALLE_VOTO (
  id INTEGER NOT NULL AUTO_INCREMENT,
  id_candidato INTEGER NOT NULL,
  id_voto INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_candidato) REFERENCES bd1_p1.CANDIDATO (id),
  FOREIGN KEY (id_voto) REFERENCES bd1_p1.VOTO (id)
);
`;

/* Script para borrar el modelo */
const script_delete_model = `
  -- BORRAR BASE DE DATOS
  DROP DATABASE IF EXISTS bd1_p1;
  -- BORRAR TABLA PARTIDO
  DROP TABLE IF EXISTS bd1_p1.PARTIDO;
  -- BORRAR TABLA CARGO
  DROP TABLE IF EXISTS bd1_p1.CARGO;
  -- BORRAR TABLA CANDIDATO
  DROP TABLE IF EXISTS bd1_p1.CANDIDATO;
  -- BORRAR TABLA CIUDADANO
  DROP TABLE IF EXISTS bd1_p1.CIUDADANO;
  -- BORRAR TABLA DEPARTAMENTO
  DROP TABLE IF EXISTS bd1_p1.DEPARTAMENTO;
  -- BORRAR TABLA MESA
  DROP TABLE IF EXISTS bd1_p1.MESA;
  -- BORRAR TABLA VOTO
  DROP TABLE IF EXISTS bd1_p1.VOTO;
  -- BORRAR TABLA DETALLE VOTO
  DROP TABLE IF EXISTS bd1_p1.DETALLE_VOTO;
`;

module.exports = { script_create_model, script_delete_model};